Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = "generic/ubuntu2004"
      master.vm.network "forwarded_port", guest: 6443, host: 6443
      master.vm.provision "shell", path: "ansible/bootstrap.sh"
    end
  
    config.vm.define "worker1" do |worker1|
      worker1.vm.box = "generic/ubuntu2004"
      worker1.vm.provision "shell", path: "ansible/bootstrap.sh"
    end
  
    config.vm.define "worker2" do |worker2|
      worker2.vm.box = "generic/ubuntu2004"
      worker2.vm.provision "shell", path: "ansible/bootstrap.sh"
    end
  end
  